apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "dpg-client.fullname" . }}-tls-cert
  namespace: {{ .Values.namespace.name }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef:
    name: le-issuer
    kind: ClusterIssuer
  dnsNames:
    {{ toYaml .Values.ingress.tls.hosts | indent 4 }}
